# Import Library Tensorflow

In [308]:
import tensorflow as tf

# Tensor dengan Shape(5,5) dengan nilai Random yang disimpan dalam Variable Random_Tensor.

In [309]:
random_tensor = tf.random.normal([5,5])
random_tensor.numpy()

array([[-0.56042594, -0.27749428,  0.51255924,  0.8010185 ,  0.51520437],
       [ 1.468342  , -0.7303449 ,  0.6806971 , -0.25614354,  0.22638038],
       [-0.41275328,  0.40714636,  1.1710836 ,  0.5506645 , -0.5771368 ],
       [ 0.9128637 , -0.11637128,  1.6163776 ,  1.7190369 , -0.43684012],
       [ 0.16972308,  1.0975889 ,  1.0428737 ,  1.2510941 , -0.04125828]],
      dtype=float32)

# Tensor dengan Shape(5,5) dari sebuah list dengan nilai Bilangan Prima dalam Variable Prime_Tensor.

In [310]:
prime_tensor = tf.convert_to_tensor(
    [[1,3,5,7,11], 
    [13, 17, 19, 23, 29], 
    [31, 37, 41, 43, 47], 
    [53, 59, 61, 67, 71], 
    [73, 79, 83, 89, 97]], dtype=tf.float32)

In [311]:
print(prime_tensor)

tf.Tensor(
[[ 1.  3.  5.  7. 11.]
 [13. 17. 19. 23. 29.]
 [31. 37. 41. 43. 47.]
 [53. 59. 61. 67. 71.]
 [73. 79. 83. 89. 97.]], shape=(5, 5), dtype=float32)


# Tampilkan Dimensi dari Kedua Variabel

In [312]:
print("Dimensi dari")
print("random_tensor :",random_tensor.shape)
print("prime_tensor  :",prime_tensor.shape)

Dimensi dari
random_tensor : (5, 5)
prime_tensor  : (5, 5)


# Hasil Perhitungan Aritmatika 2 Variabel, Gunakan Minimal 5 Operator

## Penjumlahan

In [313]:
x = random_tensor
y = prime_tensor
tf.add(x,y)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 0.43957406,  2.7225058 ,  5.5125594 ,  7.8010187 , 11.515204  ],
       [14.468342  , 16.269655  , 19.680696  , 22.743856  , 29.226381  ],
       [30.587246  , 37.407146  , 42.171085  , 43.550663  , 46.422863  ],
       [53.912865  , 58.88363   , 62.61638   , 68.71904   , 70.563156  ],
       [73.16972   , 80.09759   , 84.04288   , 90.25109   , 96.95874   ]],
      dtype=float32)>

## Pengurangan

In [314]:
tf.subtract(x,y)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ -1.560426 ,  -3.2774942,  -4.4874406,  -6.1989813, -10.484796 ],
       [-11.531658 , -17.730345 , -18.319304 , -23.256144 , -28.773619 ],
       [-31.412754 , -36.592854 , -39.828915 , -42.449337 , -47.577137 ],
       [-52.087135 , -59.11637  , -59.38362  , -65.28096  , -71.436844 ],
       [-72.83028  , -77.90241  , -81.95712  , -87.74891  , -97.04126  ]],
      dtype=float32)>

## Perkalian

In [315]:
tf.multiply(x,y)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ -0.56042594,  -0.8324828 ,   2.562796  ,   5.607129  ,
          5.6672482 ],
       [ 19.088446  , -12.415863  ,  12.933245  ,  -5.8913016 ,
          6.565031  ],
       [-12.795352  ,  15.064416  ,  48.014427  ,  23.678574  ,
        -27.125431  ],
       [ 48.381775  ,  -6.865906  ,  98.59903   , 115.175476  ,
        -31.015648  ],
       [ 12.389785  ,  86.709526  ,  86.55852   , 111.347374  ,
         -4.0020533 ]], dtype=float32)>

## Pembagian

In [316]:
tf.divide(x,y)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-5.60425937e-01, -9.24980938e-02,  1.02511846e-01,
         1.14431210e-01,  4.68367599e-02],
       [ 1.12949379e-01, -4.29614633e-02,  3.58261615e-02,
        -1.11366753e-02,  7.80622009e-03],
       [-1.33146225e-02,  1.10039562e-02,  2.85630133e-02,
         1.28061511e-02, -1.22795068e-02],
       [ 1.72238424e-02, -1.97239453e-03,  2.64979936e-02,
         2.56572682e-02, -6.15267782e-03],
       [ 2.32497370e-03,  1.38935307e-02,  1.25647439e-02,
         1.40572367e-02, -4.25343111e-04]], dtype=float32)>

## Pangkat

In [317]:
tf.pow(x,y)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-5.6042594e-01, -2.1367913e-02,  3.5376944e-02,  2.1159126e-01,
         6.7885173e-04],
       [ 1.4748697e+02, -4.7860355e-03,  6.7007577e-04, -2.4838099e-14,
         1.9513027e-19],
       [-1.2201315e-12,  3.6372302e-15,  6.4878888e+02,  7.2134642e-12,
        -6.0270192e-12],
       [ 7.9710213e-03, -0.0000000e+00,  5.2615305e+12,  5.8091016e+15,
        -2.9033443e-26],
       [ 0.0000000e+00,  1.5658015e+03,  3.2601212e+01,  4.5583530e+08,
        -0.0000000e+00]], dtype=float32)>

# Nilai Maksimum dan Minimum dari Variabel Random-Tensor

In [318]:
print("Nilai Maksimal Variabel random_tensor : ", tf.argmax(random_tensor))
print("Nilai Minimal Variabel random_tensor  : ", tf.argmin(random_tensor))

Nilai Maksimal Variabel random_tensor :  tf.Tensor([1 4 3 3 0], shape=(5,), dtype=int64)
Nilai Minimal Variabel random_tensor  :  tf.Tensor([0 1 0 1 2], shape=(5,), dtype=int64)


# Penggabungan Variable Random_Tensor dengan Prime_Tensor (concatenation)

In [319]:
print("Penggabungan kolom")
concat = tf.concat([random_tensor,prime_tensor], axis=0)
concat

Penggabungan kolom


<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[-5.6042594e-01, -2.7749428e-01,  5.1255924e-01,  8.0101848e-01,
         5.1520437e-01],
       [ 1.4683419e+00, -7.3034489e-01,  6.8069708e-01, -2.5614354e-01,
         2.2638038e-01],
       [-4.1275328e-01,  4.0714636e-01,  1.1710836e+00,  5.5066448e-01,
        -5.7713681e-01],
       [ 9.1286367e-01, -1.1637128e-01,  1.6163776e+00,  1.7190369e+00,
        -4.3684012e-01],
       [ 1.6972308e-01,  1.0975889e+00,  1.0428737e+00,  1.2510941e+00,
        -4.1258283e-02],
       [ 1.0000000e+00,  3.0000000e+00,  5.0000000e+00,  7.0000000e+00,
         1.1000000e+01],
       [ 1.3000000e+01,  1.7000000e+01,  1.9000000e+01,  2.3000000e+01,
         2.9000000e+01],
       [ 3.1000000e+01,  3.7000000e+01,  4.1000000e+01,  4.3000000e+01,
         4.7000000e+01],
       [ 5.3000000e+01,  5.9000000e+01,  6.1000000e+01,  6.7000000e+01,
         7.1000000e+01],
       [ 7.3000000e+01,  7.9000000e+01,  8.3000000e+01,  8.9000000e+01,
      

In [320]:
print("Penggabungan baris")
concat = tf.concat([random_tensor,prime_tensor], axis=1)
concat

Penggabungan baris


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[-5.6042594e-01, -2.7749428e-01,  5.1255924e-01,  8.0101848e-01,
         5.1520437e-01,  1.0000000e+00,  3.0000000e+00,  5.0000000e+00,
         7.0000000e+00,  1.1000000e+01],
       [ 1.4683419e+00, -7.3034489e-01,  6.8069708e-01, -2.5614354e-01,
         2.2638038e-01,  1.3000000e+01,  1.7000000e+01,  1.9000000e+01,
         2.3000000e+01,  2.9000000e+01],
       [-4.1275328e-01,  4.0714636e-01,  1.1710836e+00,  5.5066448e-01,
        -5.7713681e-01,  3.1000000e+01,  3.7000000e+01,  4.1000000e+01,
         4.3000000e+01,  4.7000000e+01],
       [ 9.1286367e-01, -1.1637128e-01,  1.6163776e+00,  1.7190369e+00,
        -4.3684012e-01,  5.3000000e+01,  5.9000000e+01,  6.1000000e+01,
         6.7000000e+01,  7.1000000e+01],
       [ 1.6972308e-01,  1.0975889e+00,  1.0428737e+00,  1.2510941e+00,
        -4.1258283e-02,  7.3000000e+01,  7.9000000e+01,  8.3000000e+01,
         8.9000000e+01,  9.7000000e+01]], dtype=float32)>

# Hasil Sorting dari Kedua Variabel diatas (Descending)

In [321]:
print("Sorting random_tensor Descending")
print(tf.sort(random_tensor,direction="DESCENDING"))

Sorting random_tensor Descending
tf.Tensor(
[[ 0.8010185   0.51520437  0.51255924 -0.27749428 -0.56042594]
 [ 1.468342    0.6806971   0.22638038 -0.25614354 -0.7303449 ]
 [ 1.1710836   0.5506645   0.40714636 -0.41275328 -0.5771368 ]
 [ 1.7190369   1.6163776   0.9128637  -0.11637128 -0.43684012]
 [ 1.2510941   1.0975889   1.0428737   0.16972308 -0.04125828]], shape=(5, 5), dtype=float32)


In [322]:
print("Sorting prime_tensor Descending")
print(tf.sort(prime_tensor,direction="DESCENDING"))

Sorting prime_tensor Descending
tf.Tensor(
[[11.  7.  5.  3.  1.]
 [29. 23. 19. 17. 13.]
 [47. 43. 41. 37. 31.]
 [71. 67. 61. 59. 53.]
 [97. 89. 83. 79. 73.]], shape=(5, 5), dtype=float32)
